name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-node@master
    - uses: c-hive/gha-yarn-cache@v2

    - name: Install node modules
      run: |
        yarn install
    - name: Run test
      run: |
        yarn lint